# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jakkrapat
email: ampring@jakkrapat.com
description: >- # this means to ignore newlines until "baseurl:"
  พื้นที่แชร์เรื่องราวและสิ่งต่างๆ ที่ได้เรียนรู้ในชีวิตของผม
  พยายามจะเป็น Life Long Learner พัฒนาตัวเองให้ดีขึ้น
  วันละ 1% ให้ได้ในทุกๆ วัน    

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jakkrapat.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: guitarjakk
github_username:  guitarjak 

# Added my site's branding
author: G. Jakkrapat 
copyright: "Jakkrapat Ampring"
facebook_username: guitar7424
linkedin_username: guitarjkp
twitter_username: guitarjakk

# Build settings
# Removed minima theme as it is now a regular theme
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
